_wandb:
    value:
        cli_version: 0.21.0
        e:
            e6mdodd9budfp8faerk2pt6lx9xtrbxv:
                apple:
                    ecpuCores: 2
                    gpuCores: 14
                    memoryGb: 16
                    name: Apple M1 Pro
                    pcpuCores: 6
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "26843545600"
                args:
                    - --config
                    - config_with_wandb.yaml
                codePath: train_with_wandb.py
                codePathLocal: train_with_wandb.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "994662584320"
                        used: "742666358784"
                email: yfeng@berkeley.edu
                executable: /Users/richie/Desktop/git.nosync/assignment1-basics/.venv/bin/python3
                git:
                    commit: db676cc9bf371be116b6b64f9b59a6eed25fc348
                    remote: https://github.com/richiefeng/assignment1-basics.git
                host: Richies-MacBook-Pro-4.local
                memory:
                    total: "17179869184"
                os: macOS-15.5-arm64-arm-64bit
                program: /Users/richie/Desktop/git.nosync/assignment1-basics/train_with_wandb.py
                python: CPython 3.11.2
                root: /Users/richie/Desktop/git.nosync/assignment1-basics
                startedAt: "2025-08-23T23:38:03.444890Z"
                writerId: e6mdodd9budfp8faerk2pt6lx9xtrbxv
        m: []
        python_version: 3.11.2
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 15
                - 16
            "4": 3.11.2
            "5": 0.21.0
            "12": 0.21.0
            "13": darwin-arm64
batch_size:
    value: 32
betas:
    value:
        - 0.9
        - 0.999
context_length:
    value: 256
cosine_cycle_iters:
    value: 10000
d_ff:
    value: 1344
d_model:
    value: 512
eps:
    value: "1e-8"
grad_clip_norm:
    value: 1
learning_rate:
    value: "1e-4"
max_learning_rate:
    value: "1e-3"
min_learning_rate:
    value: "1e-5"
num_epochs:
    value: 100
num_heads:
    value: 16
num_layers:
    value: 4
rope_theta:
    value: 10000
system_info:
    value:
        cpu_count: 8
        cwd: /Users/richie/Desktop/git.nosync/assignment1-basics
        platform: darwin
        python_version: 3.11.2
torch_info:
    value:
        cuda_available: false
        cuda_version: null
        mps_available: true
        torch_version: 2.6.0
train_data_path:
    value: data/TinyStoriesV2-GPT4-train.txt
use_lr_schedule:
    value: true
val_data_path:
    value: data/TinyStoriesV2-GPT4-valid.txt
vocab_size:
    value: 10000
warmup_iters:
    value: 1000
weight_decay:
    value: 0.01
